### PR TITLE
Mass cleanup

### PR DESCRIPTION
**Pull request by night**

### CODE REVIEW

**Comment by amclay** [comment]
+1

**Comment by Fugiman** [comment]
Thanks!

**Comment by AnUnknownMiner** [comment]
:+1: Thanks for this giant cleanup, night!

**Comment by Fasani** [comment]
I noticed you use http://webchat.freenode.net/?channels=twitch-api

Have you looked into: https://gitter.im/

very nice...

**Comment by bashtech** [comment]
Unless there is an option to connect to an existing IRC channel I don't
think that would fit our community.

**Pull request merged**
