### PR TITLE
added HTML 5 player version

### PR DESCRIPTION
**Pull request by ST6Daniel**
Added HTML 5 player version

### CODE REVIEW

**Comment by ST6Daniel** [comment]
Oh btw, test results reveal up to 52% less CPU usage on my i7-2600k @ 4.5 GHz! :)

**Comment by mrjumjum** [comment]
That is not a part of our official API. Thank you for your suggestion.

**Comment by ST6Daniel** [comment]
How soon will this be integrated into your official API ? It is already running stable on all browsers, isn't it?

**Comment by 3ventic** [comment]
@ST6Daniel I don't think it will be a supported option for developers to control. HTML5 will be used by default and browsers that don't support it will use Flash as a fallback, but the HTML5 player isn't fully released yet.

**Comment by ST6Daniel** [comment]
Thank you very much for the detailed and fast reply 3ventic! :) Are you one of the Twitch DEVs working on that HTML5 integration? Cause it works fine on my Firefox... :) (We can save millions and millions of dollar/€ annually moving finally to HTML5 player on twitch! 50% CPU decrease is also massive electricity decrease! :) And then everyone can finally watch a stream and play at same time (dual screens)

**Comment by 3ventic** [comment]
@ST6Daniel I don't work on it, no. I'm speaking as just another 3rd party dev. I've just been around for a long time and seen how things generally go.

**Pull request closed without merging**
