### PR TITLE
Added anonymously login for chat.

### PR DESCRIPTION
**Pull request by Megaxela**
Not sure about 6 digits number, but web version using it for anonymous login.

### CODE REVIEW

**Comment by Bekey** [comment]
I've successfully logged in anonymously with empty passwords.

**Comment by Megaxela** [comment]
Oh, seriously? Feeling pretty stupid. Well, I just didn't think, that I can
call command without args.
But otherwise, why documentation doesn't contains this info? (Or I am just
so blind)
When I'll reach PC, I'll cancel pull request.

**Comment by Bekey** [comment]
Wait, I'm dumb.

Not sending a PASS command at all works too, but if you DO send a PASS command it has to be "blah".

I apologize.

**Comment by Megaxela** [comment]
Oh, well, I'll change pull request, according this info and resend it.
Thank you for participating!

Wait, I'm dumb.

Not sending a PASS command at all works too, but if you DO send a PASS
command it has to be "blah".

I apologize.

—
Reply to this email directly or view it on GitHub
<https://github.com/justintv/Twitch-API/pull/507#issuecomment-196495014>.

**Comment by Megaxela** [comment]
Oh, just saw your last line in comment. I answered through e-mail, so and I didn't see it. 
Well, I reopened it.

**Pull request closed without merging**
